name: Deploy docs

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
            version: 8
            run_install: false
    

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Deploy
        working-directory: ./packages/docs
        run: pnpm deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}